name: Build & Publish Package

on:
  workflow_call:
    inputs:
      increment:
        required: true
        type: string
      preid:
        required: false
        type: string

env:
  NODE_VERSION: 22

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: |
          git config --global user.name 'AboutBits Tech'
          git config --global user.email 'tech@aboutbits.it'
      - uses: aboutbits/github-actions-node/setup-and-install@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Get current package version
        id: currentVersion
        run: echo "currentVersion=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Validate prerelease increment
        if: github.event.inputs.increment == 'prerelease' && !contains(steps.currentVersion.outputs.currentVersion, '-')
        run: exit 1
      - name: npm version
        run: |
          if [ -n "${{ github.event.inputs.preid }}" ]; then
            npm version ${{ github.event.inputs.increment }} --preid ${{ github.event.inputs.preid }}
          else
            npm version ${{ github.event.inputs.increment }}
          fi
      - name: Get next package version
        id: nextVersion
        run: echo "nextVersion=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create GitHub release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v${{ steps.nextVersion.outputs.nextVersion }}',
              name: 'v${{ steps.nextVersion.outputs.nextVersion }}',
              prerelease: '${{ steps.nextVersion.outputs.nextVersion }}'.includes('-')
            })
